---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/signin":
    post:
      summary: Signin user
      tags:
      - Authenticate User
      parameters: []
      responses:
        '200':
          description: Successfully signed in
          examples:
            application/json:
              email: foobar@example.com
              password: '123456'
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/user":
    post:
      summary: Signup without a referral
      tags:
      - SignUp
      parameters: []
      responses:
        '201':
          description: Signup Successful
          examples:
            application/json:
              first_name: Foo
              last_name: Bar
              email: foobar@example.com
              password: '123456'
          content: {}
        '422':
          description: invalid request
          examples:
            application/json:
              first_name: Foo
              last_name: Bar
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - first_name
              - last_name
              - email
              - password
    get:
      summary: Gets currently signed in User
      tags:
      - Fetch User
      responses:
        '200':
          description: User found
          examples:
            application/json: {}
          content: {}
        '401':
          description: invalid Authentication
          examples:
            application/json: {}
          content: {}
  "/api/v1/signup/{referral_token}":
    post:
      summary: Signup with referral link
      tags:
      - SignUp with a referral link
      parameters:
      - name: referral_token
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Signup Successful with $10 reward
          examples:
            application/json:
              first_name: Foo
              last_name: Bar
              email: foobar@example.com
              password: '123456'
          content: {}
        '422':
          description: invalid request
          examples:
            application/json:
              first_name: Foo
              last_name: Bar
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - first_name
              - last_name
              - email
              - password
  "/api/v1/referral_link":
    get:
      summary: Get Referral Link
      tags:
      - Get Logged in User referral link
      responses:
        '200':
          description: User found
          examples:
            application/json: {}
          content: {}
        '401':
          description: invalid Authentication
          examples:
            application/json: {}
          content: {}
  "/api/v1/rewards":
    get:
      summary: Get Rewards for logged in User
      tags:
      - Get Rewards
      responses:
        '200':
          description: User found
          examples:
            application/json: {}
          content: {}
        '401':
          description: invalid Authentication
          examples:
            application/json: {}
          content: {}
  "/api/v1/referred_users":
    get:
      summary: Get Registered User invited by Logged in user
      tags:
      - Get Invited registered users
      responses:
        '200':
          description: User found
          examples:
            application/json: {}
          content: {}
        '401':
          description: invalid Authentication
          examples:
            application/json: {}
          content: {}
  "/api/v1/invite":
    post:
      summary: Sends referral invitation to emails
      tags:
      - Send invite to Users
      parameters: []
      responses:
        '200':
          description: Invitation was sent Successfully
          examples:
            application/json:
              message: Invitations successfully sent
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                emails:
                  type: array
                  description: emails of users to invite
                  items:
                    type: string
              required:
              - emails
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
